### ISSUE TITLE
archiveRetriever Unusable After Updating to Latest Packages?

### ISSUE THREAD

**Issue by stefansmr** [liserman/archiveRetriever#5]
Hi liserman,

I have definitely appreciated this package so far! It has been immensely helpful for my job. However, after going through and updating my R packages in RStudio last week, I noticed today I was no longer able to run any of the following functions:

```
library(archiveRetriever)

archive_list <- archiveRetriever::archive_overview(
  homepage = "elections.alaska.gov/",
  startDate = "2024-01-01",
  endDate = "2024-02-01"
)


archive_list <- archiveRetriever::retrieve_urls(
  homepage = "elections.alaska.gov/",
  startDate = "2024-01-01",
  endDate = "2024-02-01"
)

```

I was hoping you could help me determine which packages might need to be reverted? I appreciate your time and help!

**Comment by liserman** [comment]
Hi,
thanks for liking my package and your bug report. 
I had a look into the problem you described. While I could not figure out any issues with dependencies, I discovered and fixed an issue in the code of the two functions that should solve your issue. 
I just resubmitted an updated version of the package (version 0.4.0) to CRAN which should be up and running within the next day. In the meantime you can access the updated version via github using `devtools::install_github("liserman/archiveRetriever")`
